name: flutter_learning
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #flutter国际化
  flutter_localizations:
    sdk: flutter
  #flare_rive动画
  flare_flutter: ^3.0.0
  #状态管理
  provider: ^5.0.0
  #农历日历
#  chinese_calendar: ^0.0.2
#  my_chinese_calendar:
#    path: ./plugins/my_chinese_calendar
  #日历插件
#  flutter_calendar: ^0.0.9
#  flutter_calendar:
#    path: ./plugins/flutter_calendar
  #pageView 日历
  table_calendar: ^3.0.0
#  my_calendar_strip:
#    path: ./plugins/my_flutter_calendar_strip
  #扫码
#  qrscan:
#    path: ./plugins/qrscan-0.2.17
  #地图
  map: ^0.3.0
#  flutter_map: ^0.10.1+1
#  flutter_bmfmap: ^1.0.2
  sensors: ^2.0.0
  #工具人
  common_utils: ^2.0.2
  image_picker: ^0.7.4
  #Stream变体
  rxdart: ^0.26.0
  #获取wifi信息
#  wifi_info_plugin: ^1.1.5
#  wifi:
#    path:  ./plugins/wifi-0.1.5
  #权限管理
  permission_handler: ^6.1.3
  url_launcher: ^6.0.3
  fluttertoast: ^8.0.5
  #浮动提示
#  ffloat: ^1.0.1
  #刷新组件
#  frefresh: ^1.1.0
  #轻量文件读写
  shared_preferences: ^2.0.5
  #步骤引导
#  flutter_guidance_plugin: ^0.0.3
  #静态html 不能插入视频
  flutter_html: ^2.0.0-nullsafety.0
  #不能嵌入widget中，但性能较好
#  flutter_webview_plugin: ^0.3.11
  #添加了视频插入 兼容性不行
#  markdown_widget: ^1.1.9
  #最好用的markdown
  flutter_markdown: ^0.6.1
  #富文本编辑器
#  zefyr_plus: ^0.10.5
#  notus: ^0.1.5
  #生成二维码
  qr_flutter: ^4.0.0
  #获取设备图片/视频资源
#  photo_album_manager: ^1.1.7
  #flutter版本控制
#  fvm: ^1.3.3
  #注解解析
  source_gen: ^1.0.0
  path_provider: ^2.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
